### ISSUE TITLE
NoMethodError in resource creation form with belongs_to attribute

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#27]
In `belongs_to.rb` at line 7

`undefined method `foreign_key' for nil:NilClass`

**Comment by vala** [comment]
@gabriel-cardoso This means that `ModelFieldParsers::Relation` added a `BelongsTo` field to your model but the model can't find the relation with the given name. Since relations are fetched from the same `ActiveRecord::Base.reflections` hash when creating the `BelongsTo` field than the one used when trying to fetch the relation from inside the field class, there's something happening that I can't guess from the information that you gave to me
