### ISSUE TITLE
Save&Edit submit button does not work for singleton resource

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#30]
I think we can just keep the save button for singleton resources. Even "Cancel" doesn't mean something here.

**Comment by vala** [comment]
Yes, @xana68 submitted the same feedback on the dashboard, we need to see how do we want to manage this since actions are rendered inside the `_form` partial, and that I'd like to let users use the same model inside `Singleton` and `Crud` components at the same time, so the solution should take that into account. Maybe, some kind of per-component settings, allowing the `form.actions` call to take paramaters, that could be avoided when you want to keep the default behavior

The `FormBuilder#actions` method is defined here : https://github.com/para-cms/para/blob/master/lib/para/form_builder/containers.rb#L10

**Comment by vala** [comment]
The code to allow options could look like this

```ruby
def actions(options = {}, &block)
  template.content_tag(:div, class: 'block form-actions') do
    template.content_tag(:div, class: 'col-sm-9 col-sm-offset-3') do
      if block
        template.capture(&block)
      else
        action_buttons_for(options).join("\n").html_safe
      end
    end
  end
end

def action_buttons_for(options)
  names = [:submit, :submit_and_edit, :submit_and_add_another, :cancel]

  names.select! { |name| options[:only].include?(name) } if options[:only]
  names.reject! { |name| options[:except].include?(name) } if options[:except]
  
  buttons = names.map { |name| send(:"para_#{ name }_button") }
  buttons.unshift(return_to_hidden_field)
  buttons
end
```

Then we could set form options inside components and access them with something like :

```ruby
def actions(options = {}, &block)
  if options.empty?
    options[:only] = template.instance_variable_get(:@component).default_form_actions
  end
  
  # ...
end
```
